spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_flyway
    username: root
    password: root
  profiles:
    active: test

greeting:
  name: Leo
  message: Hello
  info: ${greeting.message} from ${greeting.name}

feature:
  toggleOn: true
  featureList:
  - name: Sms
    enabled: true
  - name: Wechat
    enabled: false
